- name: Clone git repository
  git: 
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ repo_version }}"
    update: true

- name: Install frontend dependencies
  command: npm install
  args: 
    chdir: "{{ repo_dest }}"

- name: Build frontend application
  command: npm run build
  args: 
    chdir: "{{ repo_dest }}"


