apiVersion: v1
kind: Secret
metadata:
  name: myelga-secrets
  namespace: myelga
type: Opaque
stringData:
  mysql-database: elga_app_schema
  mysql-root-password: "<MYSQL_ROOT_PASSWORD>"
  mysql-username: "<MYSQL_USERNAME>"
  mysql-password: "<MYSQL_PASSWORD>"
  mail-username: "<MAIL_USERNAME>"
  mail-password: "<MAIL_APP_PASSWORD>"
  jwt-secret: "<JWT_SECRET>"