apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: myelga
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.37
          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL service..."

              while ! nc -z mysql 3306; do
                echo "MySQL is unavailable. Retrying in 5 seconds..."
                sleep 5
              done

              echo "MySQL is ready."
      containers:
        - name: backend
          image: ghcr.io/tolisapostolidis/myelga-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/elga_app_schema
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: myelga-secrets
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myelga-secrets
                  key: mysql-password
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: myelga-secrets
                  key: mail-username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myelga-secrets
                  key: mail-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: myelga-secrets
                  key: jwt-secret
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10      
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi