---
- name: Restart Kubernetes deployment
  hosts: kubernetes-vm

  tasks:
    - name: Restart deployment
      command: microk8s kubectl rollout restart deployment/{{ deployment_name }} -n myelga  
      register: restart_result

    - name: Display restart result
      debug:
        msg: "{{ restart_result.stdout }}"

    - name: Wait for deployment rollout to complete
      command: microk8s kubectl rollout status deployment/{{ deployment_name }} -n myelga