---
- name: Clone git repository
  git: 
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ repo_version }}"
    update: true
  notify: Restart Docker Compose

- name: Create Docker env file
  template:
    src: env.j2
    dest: "{{ repo_dest }}/.env"

- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ repo_dest }}"
    state: absent

- name: Build and start Docker Compose services
  community.docker.docker_compose_v2:
    project_src: "{{ repo_dest }}"
    build: always
    state: present
    remove_orphans: true
  register: compose_result

- name: Display Docker Compose result
  debug:
    var: compose_result